import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect, useState } from 'react'
import Message from './Message'

export default function Home() {
  let [messages, setMessages] = useState([])
  
  useEffect(() => {
    fetch('http://localhost:3000/api/messages')
      .then(res => res.json())
      .then(data => {
        setMessages(data)
        console.log(messages)
      })
  }, [])
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>messages: </div>
        <ul>
          {messages && messages.map(m => 
          <li key={m._id}><Message message={m} /></li>)}
        </ul>
      </main>

      <footer>
        
      </footer>
    </div>
  )
}
